version: "3.8"

services:
  redis-server:
    container_name: redis-server
    image: redis:${REDIS_TAG:-latest}
    restart: always
    networks:
      - redis-pubsub
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
      - ./redis/data:/data:rw
  grafana:
    container_name: grafana
    image: grafana/grafana:${GRAFANA_TAG:-latest}
    ports:
      - ${GRAFANA_PORT:-3000}:3000
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      - GF_ENABLE_GZIP=true
      - GF_INSTALL_PLUGINS=redis-datasource
      - REDIS_HOST=${REDIS_HOST:-redis-server}
      - REDIS_PORT=${REDIS_PORT:-6379}
    networks:
      - redis-pubsub
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      # Uncomment to preserve Grafana configuration
      # - ./data:/var/lib/grafana
networks:
  redis-pubsub:
